name: publish react-logic-component

on:
  push:
    branches:
      - feat
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: use pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: use node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - name: install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: build
        run: pnpm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
